version: '3.8'

services:
  app:
    image: python:3.11-slim
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
